force-app/main/default/objects/Interface_Log__c/Interface_Log__c.object-meta.xml
<CustomObject>
    <description>Incoming and outgoing interface messages.  This table will be truncated periodically.</description>
    <label>Interface Log</label>
    <nameField>
        <displayFormat>LOG-{0000}</displayFormat>
        <label>Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interface Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interface_Log__c/fields/Interface_Name__c.field-meta.xml
<CustomField>
    <fullName>Interface_Name__c</fullName>
    <description>Customer from SAP, Quote to SAP, etc</description>
    <label>Interface Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Account from SAP</fullName>
            </value>
            <value>
                <fullName>Sales Order from SAP</fullName>
            </value>
            <value>
                <fullName>Service Order to SAP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Json_Message__c.field-meta.xml
<CustomField>
    <fullName>Json_Message__c</fullName>
    <description>The message being sent to or from an external system.</description>
    <label>Json Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Interface_Log__c/fields/Result_Details__c.field-meta.xml
<CustomField>
    <fullName>Result_Details__c</fullName>
    <description>Error or success messages associated with this integration message.</description>
    <label>Result Details</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/TestInterfaceLog.cls
@isTest
private class TestInterfaceLog {

    @isTest static void instantiateLog()
    {
        String interfaceName = 'Test Interface';
        String someJson = '{ "CompanyName" : "Illumina" }';
        Interface_Log__c log = InterfaceLog.instantiateLog(interfaceName, someJson);

        System.assertEquals(someJson, log.Json_Message__c);
        System.assertEquals(interfaceName, log.Interface_Name__c);
        System.assert(log.Id == null);
    }

    @isTest static void createLog()
    {
        String interfaceName = 'Test Interface';
        String someJson = '{ "CompanyName" : "Illumina" }';
        InterfaceLog.LogDetails logDetails = InterfaceLog.createLog(interfaceName, someJson);

        System.assertEquals(interfaceName, logDetails.interfaceName);
        System.assert(logDetails.logRecordId != null);
    }

    @isTest static void finalizeLog1()
    {
        String interfaceName = 'Test Interface';
        String someJson = '{ "CompanyName" : "Illumina" }';
        String resultDetails = 'Stunning success';
        InterfaceLog.LogDetails logDetails = InterfaceLog.createLog(interfaceName, someJson);

        InterfaceLog.finalizeLog(logDetails, InterfaceLog.RESULT_SUCCESS, resultDetails);

        Interface_Log__c savedLog = [SELECT Result__c, Result_Details__c FROM Interface_Log__c WHERE Id = :logDetails.logRecordId];
        System.assertEquals(InterfaceLog.RESULT_SUCCESS, savedLog.Result__c);
        System.assertEquals(resultDetails, savedLog.Result_Details__c);
    }

    @isTest static void finalizeLog2()
    {
        String interfaceName = 'Test Interface';
        String someJson = '{ "CompanyName" : "Illumina" }';
        String resultDetails = 'Stunning success';
        Interface_Log__c log = InterfaceLog.instantiateLog(interfaceName, someJson);

        InterfaceLog.finalizeLog(log, InterfaceLog.RESULT_SUCCESS, resultDetails);

        Interface_Log__c savedLog = [SELECT Result__c, Result_Details__c FROM Interface_Log__c WHERE Id = :log.Id];
        System.assertEquals(InterfaceLog.RESULT_SUCCESS, savedLog.Result__c);
        System.assertEquals(resultDetails, savedLog.Result_Details__c);
    }

    @isTest static void finalizeLog3()
    {
        String interfaceName = 'Test Interface';
        String someJson = '{ "CompanyName" : "Illumina" }';
        String resultDetails = 'Stunning success';
        Interface_Log__c log = InterfaceLog.instantiateLog(interfaceName, someJson);

        InterfaceLog.finalizeLog(log, InterfaceLog.RESULT_SUCCESS, resultDetails, false);

        System.assertEquals(InterfaceLog.RESULT_SUCCESS, log.Result__c);
        System.assert(log.Id == null);
        System.assertEquals(resultDetails, log.Result_Details__c);
    }

}